// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NonoBlazor.Database.Contexts;

namespace NonoBlazor.Database.Migrations
{
    [DbContext(typeof(NonogramContext))]
    partial class NonogramContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("NonoBlazor.Shared.StandardNonogram", b =>
                {
                    b.Property<int>("StandardNonogramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColumnValues")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RowValues")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("StandardNonogramID");

                    b.ToTable("StandardNonograms");

                    b.HasData(
                        new
                        {
                            StandardNonogramID = 1,
                            ColumnValues = "3,3,3,3,3,3,3,3,3,3",
                            Height = 10,
                            RowValues = "3,3,3,3,3,3,3,3,3,3",
                            Width = 10
                        },
                        new
                        {
                            StandardNonogramID = 2,
                            ColumnValues = "3,3,3,3,3,3,3,3,3,3",
                            Height = 10,
                            RowValues = "3,3,3,3,3,3,3,3,3,3",
                            Width = 10
                        },
                        new
                        {
                            StandardNonogramID = 3,
                            ColumnValues = "3,3,3,3,3,3,3,3,3,3",
                            Height = 10,
                            RowValues = "3,3,3,3,3,3,3,3,3,3",
                            Width = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
