// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NonoBlazor.Database.Contexts;

namespace NonoBlazor.Database.Migrations
{
    [DbContext(typeof(NonogramContext))]
    partial class NonogramContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("NonoBlazor.Shared.StandardNonogram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColumnValues")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PublicID")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowValues")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("StandardNonograms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ColumnValues = "3,3,3,3,3,3,3,3,3,3",
                            Height = 10,
                            PublicID = new Guid("cc5f50ad-3c3c-452c-8d9f-43396b46664b"),
                            RowValues = "3,3,3,3,3,3,3,3,3,3",
                            Width = 10
                        },
                        new
                        {
                            ID = 2,
                            ColumnValues = "3,3,3,3,3,3,3,3,3,3",
                            Height = 10,
                            PublicID = new Guid("ea6ef215-d7e1-4f82-8cd4-b83e56e8c40d"),
                            RowValues = "3,3,3,3,3,3,3,3,3,3",
                            Width = 10
                        },
                        new
                        {
                            ID = 3,
                            ColumnValues = "3,3,3,3,3,3,3,3,3,3",
                            Height = 10,
                            PublicID = new Guid("8d1388be-25d0-40b5-b7aa-8c204dea4247"),
                            RowValues = "3,3,3,3,3,3,3,3,3,3",
                            Width = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
